# Generated by Django 5.0.6 on 2024-06-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='video',
        ),
    ]
